### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by bogdanr** [Matty9191/bind-query-log-statistics#1]
Hello,

I am using your script like this:
`./bind-query-log-stats.py /var/log/bind9/query.log`
and I get this output:
```
Processing logfile /var/log/bind9/query.log

Summary for 18-Jan-2018 07:54:51.603 - 18-Jan-2018 08:32:27.532

Total DNS_QUERIES processed : 2583
  +E     records requested : 2583

Top  100  DNS names requested:
  IN : 2583

Top  100  DNS clients:
Traceback (most recent call last):
  File "./bind-query-log-stats.py", line 268, in <module>
    print_top_dns_clients(COUNT)
  File "./bind-query-log-stats.py", line 105, in print_top_dns_clients
    client_name = socket.gethostbyaddr(client_ip)[0]
socket.gaierror: [Errno -2] Name or service not known
```

My log format is like this:
`tail -1 /var/log/bind9/query.log`
```
18-Jan-2018 08:36:30.387 client 173.90.213.148#9307 (edu.za): query: edu.za IN ANY +E (172.31.7.30)
```

**Comment by Matty9191** [comment]
Which version of bind are you running? Could you paste that to the issue?

**Comment by bogdanr** [comment]
BIND 9.10.3-P4-Debian <id:ebd72b3>

And my config for logging looks like this:
```
logging {
  channel "querylog" {
    file "/var/log/bind9/query.log";
    print-time yes;
  };
  category queries { querylog; };

        channel update_debug {
                file "/var/log/bind9/update_debug.log" versions 3 size 100k;
                severity debug;
                print-severity  yes;
                print-time      yes;
        };
        channel security_info {
                file "/var/log/bind9/security_info.log" versions 1 size 100k;
                severity info;
                print-severity  yes;
                print-time      yes;
        };
        channel bind_log {
                file "/var/log/bind9/bind.log" versions 3 size 1m;
                severity info;
                print-category  yes;
                print-severity  yes;
                print-time      yes;
        };

        category default { bind_log; };
        category lame-servers { null; };
        category update { update_debug; };
        category update-security { update_debug; };
        category security { security_info; };
};
```

**Comment by Matty9191** [comment]
Thanks for the response. Are you using Bind views? I assume not.

**Comment by bogdanr** [comment]
No. I am not using views.

**Comment by Matty9191** [comment]
I just posted a new version. Can you try it out and let me know if you see any issues?

**Comment by bogdanr** [comment]
Works like a charm!
Thanks!
